autoselect/autoselect/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('parsing.urls', namespace='parsing')),
    path('analogs/', include('parsing.urls', namespace='parsing')),
    path('analogs/<marking>/', include('parsing.urls', namespace='parsing')),
    path('not_found/', include('parsing.urls', namespace='parsing')),
    path('admin/', admin.site.urls),
]

autoselect/parsing/urls.py
from django.urls import path
from . import views

app_name = 'parsing'

urlpatterns = [
    path('', views.index, name='index'),
    path('analogs/', views.analogs, name='analogs'),
    path('analogs/<marking>/', views.analog_detail, name='analog_detail'),
    path('not_found/', views.not_found, name='not_found'),
]

autoselect/parsing/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

# Create your models here.

User = get_user_model()

class Sensor(models.Model):
    # Общие и индуктивные
    marking = models.CharField(max_length=120)
    sens_type = models.CharField(max_length=30)
    case_size = models.CharField(max_length=30, null=True, blank=True)
    mounting = models.CharField(max_length=30, null=True, blank=True)
    sensing_distance = models.FloatField(null=True, blank=True)
    connection_type = models.CharField(max_length=30, null=True, blank=True)
    connector = models.CharField(max_length=30, null=True, blank=True)
    cable_length = models.FloatField(null=True, blank=True)
    housing = models.CharField(max_length=30, null=True, blank=True)
    standard_size = models.FloatField(null=True, blank=True)
    length = models.FloatField(null=True, blank=True)
    type_shell = models.CharField(max_length=30, null=True, blank=True)
    size_frame = models.CharField(max_length=30, null=True, blank=True)
    type_current = models.CharField(max_length=30, null=True, blank=True)
    current = models.CharField(max_length=30, null=True, blank=True)
    voltage = models.CharField(max_length=30, null=True, blank=True)
    contact_structure = models.CharField(max_length=30, null=True, blank=True)
    frequency = models.FloatField(null=True, blank=True)
    indication = models.CharField(max_length=30, null=True, blank=True)
    electr_protection = models.CharField(max_length=30, null=True, blank=True)
    degree_of_protect = models.CharField(max_length=30, null=True, blank=True)
    num_wires = models.FloatField(null=True, blank=True)
    temp_range = models.CharField(max_length=30, null=True, blank=True)
    class_temp = models.CharField(max_length=30, null=True, blank=True)
    work_dist = models.CharField(max_length=30, null=True, blank=True)
    special_assign = models.CharField(max_length=30, null=True, blank=True)
    wiring = models.CharField(max_length=30, null=True, blank=True)
    manufacture = models.CharField(max_length=30, null=True, blank=True)
    delay_range = models.CharField(max_length=30, null=True, blank=True)
    adjustment_speed_range = models.CharField(max_length=30, null=True, blank=True)
    trip_delay = models.CharField(max_length=30, null=True, blank=True)
    umax = models.CharField(max_length=30, null=True, blank=True)
    irab = models.CharField(max_length=30, null=True, blank=True)
    ground = models.CharField(max_length=30, null=True, blank=True)
    max_pressure = models.FloatField(null=True, blank=True)
    special_electrical_param = models.CharField(max_length=30, null=True, blank=True)
    vibro_resist = models.CharField(max_length=30, null=True, blank=True)
    out_analog_signal = models.CharField(max_length=30, null=True, blank=True)
    linear_area = models.CharField(max_length=30, null=True, blank=True)
    hole_diameter = models.FloatField(null=True, blank=True)
    slot_width = models.FloatField(null=True, blank=True)
    ex_marking = models.CharField(max_length=30, null=True, blank=True)
    special_version = models.CharField(max_length=30, null=True, blank=True)
    # Оптические
    breaker_type = models.CharField(max_length=30, null=True, blank=True)
    range_dist = models.CharField(max_length=30, null=True, blank=True)
    spectr = models.CharField(max_length=30, null=True, blank=True)
    sensitiv_adjustment = models.CharField(max_length=30, null=True, blank=True)
    operating_principle = models.CharField(max_length=30, null=True, blank=True)
    light_spot_size = models.CharField(max_length=30, null=True, blank=True)
    resolution = models.CharField(max_length=30, null=True, blank=True)
    display = models.CharField(max_length=30, null=True, blank=True)
    repetition_accuracy = models.CharField(max_length=30, null=True, blank=True)
    response_time = models.CharField(max_length=30, null=True, blank=True)
    protected_height = models.CharField(max_length=30, null=True, blank=True)
    num_beams = models.CharField(max_length=30, null=True, blank=True)
    max_range = models.CharField(max_length=30, null=True, blank=True)
    detection = models.CharField(max_length=30, null=True, blank=True)
    safety_output = models.CharField(max_length=30, null=True, blank=True)
    safety_level = models.CharField(max_length=30, null=True, blank=True)
    # Емкостные
    sensing_surface = models.CharField(max_length=30, null=True, blank=True)
    turn_on_delay = models.CharField(max_length=30, null=True, blank=True)
    turn_off_delay = models.CharField(max_length=30, null=True, blank=True)
    dielectric_constant = models.CharField(max_length=30, null=True, blank=True)
    # Магниточувствительные
    output_function = models.CharField(max_length=30, null=True, blank=True)
    switched_power = models.CharField(max_length=30, null=True, blank=True)
    controlled_level = models.CharField(max_length=30, null=True, blank=True)
    measuring_principle = models.CharField(max_length=30, null=True, blank=True)
    # Блоки сопряжения
    load_current_electronic = models.CharField(max_length=30, null=True, blank=True)
    load_current_relay = models.CharField(max_length=30, null=True, blank=True)
    num_of_connected = models.CharField(max_length=30, null=True, blank=True)
    num_of_relay_outputs = models.CharField(max_length=30, null=True, blank=True)
    num_of_electronic_outputs = models.CharField(max_length=30, null=True, blank=True)
    # Соединители
    nut_material = models.CharField(max_length=30, null=True, blank=True)
    plug_type = models.CharField(max_length=30, null=True, blank=True)
    num_contacts = models.CharField(max_length=30, null=True, blank=True)
    view = models.CharField(max_length=30, null=True, blank=True)
    connect = models.CharField(max_length=30, null=True, blank=True)
    # Влажности и температуры
    relative_output = models.CharField(max_length=30, null=True, blank=True)
    temperature_output = models.CharField(max_length=30, null=True, blank=True)
    relative_range = models.CharField(max_length=30, null=True, blank=True)
    temperature_range = models.CharField(max_length=30, null=True, blank=True)
    relative_accuracy = models.CharField(max_length=30, null=True, blank=True)
    temperature_accuracy = models.CharField(max_length=30, null=True, blank=True)
    temp_measurement_range = models.CharField(max_length=30, null=True, blank=True)
    rel_measurement_range = models.CharField(max_length=30, null=True, blank=True)
    operating_temperature = models.CharField(max_length=30, null=True, blank=True)






    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.marking


    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('sensor-detail', args=[str(self.id)])


class Analog(models.Model):
    marking = models.CharField(max_length=120)
    marking_analog = models.ManyToManyField(Sensor)
    difference = models.JSONField(null=True, blank=True)
    mark = models.CharField(max_length=40, null=True, blank=True)
    difference1 = models.JSONField(null=True, blank=True)
    mark1 = models.CharField(max_length=40, null=True, blank=True)
    difference2 = models.JSONField(null=True, blank=True)
    mark2 = models.CharField(max_length=40, null=True, blank=True)
    difference3 = models.JSONField(null=True, blank=True)
    mark3 = models.CharField(max_length=40, null=True, blank=True)
    difference4 = models.JSONField(null=True, blank=True)
    mark4 = models.CharField(max_length=40, null=True, blank=True)
    manufacture_original = models.CharField(max_length=30, null=True, blank=True)

    
    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.marking


    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('analog-detail', args=[str(self.id)])

autoselect/parsing/forms.py
from django import forms
from .models import *

class AddForm(forms.Form):
    marking = forms.CharField(max_length=120, label="Введите маркировку:", widget=forms.TextInput(attrs={'class': 'form-input'}))

autoselect/parsing/views.py
import json
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django import forms
from . import forms, models, parse_sensor
from .models import Analog, Sensor

# Create your views here.

def search(marking):
    url = f'https://sensor-com.ru/search/?query=ВБИ-М08-45Р-1112-З'
    return HttpResponseRedirect(f'analogs/{marking}/')

# Начальная страница
def index(request):
    template = 'parsing/index.html'
    #form = forms.AddForm()
    if request.method == 'POST':
        form = forms.AddForm(request.POST)
        if form.is_valid():
            marking = form.cleaned_data['marking']
            print(form.cleaned_data)
            # Проверка есть ли запрашиваемая маркировка в базе
            marking_exists = marking is not None and Analog.objects.filter(marking=marking).exists()
            if marking_exists == True:
                return HttpResponseRedirect(f'analogs/{marking}/')
            else:
                return search(marking)

            #except:
            #try:
            #    models.Analog.objects.create(**form.cleaned_data)
            #    #return redirect('home')
            #except:
            #    form.add_error(None, 'Ошибка добавления маркировки аналога')
    else:
       form = forms.AddForm()

    return render(request, template, {'form': form})
    
# Страница со списком существующих замен
def analogs(request):
    template = 'parsing/analogs_list.html'
    analogs = Analog.objects.all
    context = {
        'list' : list,
        'analogs' : analogs,
    }
    return render(request, template, context)

# Страница для не найденной маркировки
def not_found(request):
    template = 'parsing/not_found.html'
    return render(request, template)

# Страница списка аналогов для запрашиваемой маркировки с отличиями
def analog_detail(request, marking):
    #list = get_object_or_404(Analog, marking=marking)
    data = ''
    jsonDec = json.decoder.JSONDecoder()
    mark_list = []
    mark_list.append(marking)
    # Проверка есть ли запрашиваемая маркировка в базе
    if not Analog.objects.filter(marking=marking).exists():
        # Вызывается функция для парсинга данных из подключаемого файла
        data = parse_sensor.parse_products(mark_list)
        print(data)
    if data == 'marking_not_found':
        return HttpResponseRedirect('/not_found/')
    template = 'parsing/analogs_detail.html'
    analog = Analog.objects.get(marking=marking)
    if analog.difference:
        difference = jsonDec.decode(analog.difference)
    else:
        difference = None
    
    context = {
        #'list' : list,
        'analog' : analog,
        'marking' : marking,
        'difference' : difference,
    }
    return render(request, template, context)

autoselect/templates/parsing/analogs_detail.html
{% extends 'base.html' %}
{% block title %}{{ marking }}{% endblock %}
{% block header %}{{ marking }}{% endblock %}
{% block content %}

<p>Список аналогов для {{ marking }}:</p>

<!--{{ analog.mark }} -->

<br>{% for dif in difference %}
        <ul>
           <!-- <li> -->
                {{ dif }}
           <!-- </li> -->
        </ul>  
        
        {% endfor %} 

{% endblock %}

autoselect/templates/parsing/analogs_list.html
{% extends 'base.html' %}
{% block title %}Список аналогов{% endblock %}
{% block header %}Список аналогов{% endblock %}
{% block content %}


{% for analog in analogs %}
    <a href="{% url 'parsing:analog_detail' analog.marking %}">{{ analog.marking }}</a><br>
    <!--<p><b>{{ analog.marking }}</b></p>-->
    <i>Бренд: {{ analog.manufacture_original }}</i>

    <p>
        Аналоги:

        {% for mark in analog.marking_analog.all %}
    
            {{mark.marking}}{% if not forloop.last %}, {% endif %}
    
        {% endfor %}
    </p>
    
{% if not forloop.last %}<hr>{% endif %}
{% endfor %} 

{% endblock %}

autoselect/templates/parsing/index.html
{% extends 'base.html' %}
{% block title %}Поиск аналога по маркировке{% endblock %}
{% block header %}Поиск аналога по маркировке{% endblock %}
{% block content %}

<!--<form action="{% url 'parsing:index' %}" method="post">
    {% csrf_token %}
    <label for="marking">Введите маркировку: </label>
    <input id="marking" type="text" name="name_field" value="">
    <input type="submit" value="OK">
</form> -->

<style>
    .form-input{
        width:450px;
        margin: 10px 10px 10px 0;
    }
</style>

<form action="{% url 'parsing:index' %}" method="post">
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% csrf_token %}
    <p><label for="{{ form.marking.id_for_label }}">{{form.marking.label}}&nbsp&nbsp </label>{{ form.marking }}</p>
    <div class="form-error">{{ form.marking.errors }}</div>
    <input type="submit" value="Найти">
    <p><label for="marking">Пример: ВБИ-М08-45У-1112-З</label></p>
</form>

<style>
    ul {
        text-align: right
        }
</style>

<ul>
    Доступны аналоги производителей:
</ul>
<ul>
    <a href="https://sensor-com.ru/catalog/datchiki-pozitsionirovaniya-i-nalichiya-obyektov/induktivnyie/obschepromyishlennyie-2/">Сенсор</a> (индуктивные датчики)
</ul>


{% endblock %}

autoselect/templates/parsing/not_found.html
{% extends 'base.html' %}
{% block title %}Маркировка не найдена{% endblock %}
{% block header %}Маркировка не найдена{% endblock %}
{% block content %}

<p>Воспользуйтесь следующими рекомендациями:</p>

<!--{{ analog.mark }} -->

<br>
<ul>
    <li>
        Проверьте есть ли производитель данной модели в списке на главной странице
    </li>
    <li>
        Проверьте корректность маркировки через поиск Яндекс или Google
    </li>
    <li>
        Убедитесь, есть ли данная маркировка на сайте производителя из списка
    </li>
</ul>
        

{% endblock %}